<?php

use Waadby\OperationsAgent\Services\LocalOperationsRuntime;

return [
    'runtime' => env('WAADBY_OPERATIONS_RUNTIME', LocalOperationsRuntime::class),
    'capabilities' => [
        'inventory' => true,
        'backup' => true,
        'backup_verify' => true,
        'restore_preflight' => true,
        'update_preflight' => true,
        'protocol_version' => '1',
    ],
    'application' => [
        'code' => env('WAADBY_APPLICATION_CODE', 'laravel-application'),
        'name' => env('WAADBY_APPLICATION_NAME', env('APP_NAME', 'Laravel application')),
        'environment' => env('WAADBY_APPLICATION_ENVIRONMENT', env('APP_ENV', 'production')),
        'installation_id' => env('WAADBY_APPLICATION_INSTALLATION_ID'),
        'version' => env('WAADBY_APPLICATION_VERSION', '0.0.0'),
    ],
    'enabled' => env('ACCESS_OPERATIONS_ENABLED', false),
    'restores' => [
        'apply_enabled' => env('ACCESS_OPERATIONS_RESTORE_APPLY_ENABLED', false),
        'agent_enabled' => env('WAADBY_OPERATIONS_RESTORE_AGENT_ENABLED', false),
        'require_safety_backup_production' => env('ACCESS_OPERATIONS_RESTORE_REQUIRE_SAFETY_BACKUP_PRODUCTION', true),
        'require_safety_vault_production' => env('ACCESS_OPERATIONS_RESTORE_REQUIRE_SAFETY_VAULT_PRODUCTION', true),
        'journal_path' => env('WAADBY_OPERATIONS_RESTORE_JOURNAL_PATH', storage_path('app/private/waadby-operations/restores/journals')),
        'staging_path' => env('WAADBY_OPERATIONS_RESTORE_STAGING_PATH', storage_path('app/private/waadby-operations/restores/staging')),
        'validation_path' => env('WAADBY_OPERATIONS_RESTORE_VALIDATION_PATH', storage_path('app/private/waadby-operations/restores/validation')),
        'plan_ttl_seconds' => max(60, (int) env('WAADBY_OPERATIONS_RESTORE_PLAN_TTL', 900)),
        'process_timeout_seconds' => max(30, (int) env('WAADBY_OPERATIONS_RESTORE_PROCESS_TIMEOUT', 1800)),
        'maximum_files' => max(1, (int) env('WAADBY_OPERATIONS_RESTORE_MAX_FILES', 100000)),
        'maximum_uncompressed_bytes' => max(1048576, (int) env('WAADBY_OPERATIONS_RESTORE_MAX_UNCOMPRESSED_BYTES', 10737418240)),
        'maximum_archive_bytes' => max(1048576, (int) env('WAADBY_OPERATIONS_RESTORE_MAX_ARCHIVE_BYTES', 10737418240)),
        'chunk_bytes' => min(524288, max(65536, (int) env('WAADBY_OPERATIONS_RESTORE_CHUNK_BYTES', 262144))),
        'health_path' => env('WAADBY_OPERATIONS_RESTORE_HEALTH_PATH', '/up'),
        'maintenance_secret' => env('WAADBY_OPERATIONS_RESTORE_MAINTENANCE_SECRET'),
        'integration_hold_path' => env('WAADBY_OPERATIONS_RESTORE_INTEGRATION_HOLD_PATH', storage_path('app/private/waadby-operations/restores/integration-hold.json')),
    ],
    'updates' => [
        'apply_enabled' => env('ACCESS_OPERATIONS_UPDATE_APPLY_ENABLED', false),
        'agent_enabled' => env('WAADBY_OPERATIONS_UPDATE_AGENT_ENABLED', false),
        'require_vault_production' => env('ACCESS_OPERATIONS_UPDATE_REQUIRE_VAULT_PRODUCTION', true),
        'state_path' => env('WAADBY_OPERATIONS_INSTALLED_RELEASE_PATH', storage_path('app/private/waadby-operations/installed-release.json')),
        'staging_path' => env('WAADBY_OPERATIONS_UPDATE_STAGING_PATH', storage_path('app/private/waadby-operations/releases')),
        'snapshot_path' => env('WAADBY_OPERATIONS_UPDATE_SNAPSHOT_PATH', storage_path('app/private/waadby-operations/snapshots')),
        'signing_private_key' => env('WAADBY_OPERATIONS_RELEASE_SIGNING_PRIVATE_KEY'),
        'signing_key_id' => env('WAADBY_OPERATIONS_RELEASE_SIGNING_KEY_ID'),
        'trusted_keys' => env('WAADBY_OPERATIONS_RELEASE_TRUSTED_KEYS', '{}'),
        'maximum_package_bytes' => max(1048576, (int) env('WAADBY_OPERATIONS_RELEASE_MAX_PACKAGE_BYTES', 268435456)),
        'maximum_uncompressed_bytes' => max(1048576, (int) env('WAADBY_OPERATIONS_RELEASE_MAX_UNCOMPRESSED_BYTES', 536870912)),
        'maximum_files' => max(1, (int) env('WAADBY_OPERATIONS_RELEASE_MAX_FILES', 20000)),
        'maximum_file_bytes' => max(1024, (int) env('WAADBY_OPERATIONS_RELEASE_MAX_FILE_BYTES', 67108864)),
        'chunk_bytes' => min(524288, max(65536, (int) env('WAADBY_OPERATIONS_UPDATE_CHUNK_BYTES', 262144))),
        'process_timeout_seconds' => max(30, (int) env('WAADBY_OPERATIONS_UPDATE_PROCESS_TIMEOUT', 1800)),
    ],
    'vault' => [
        'key' => env('WAADBY_OPERATIONS_VAULT_KEY'),
        'key_id' => env('WAADBY_OPERATIONS_VAULT_KEY_ID'),
        'chunk_bytes' => min(8388608, max(1048576, (int) env('ACCESS_OPERATIONS_VAULT_CHUNK_BYTES', 1048576))),
    ],
    'remote_agent' => [
        'enabled' => env('WAADBY_OPERATIONS_REMOTE_AGENT_ENABLED', false),
        'state_path' => env('WAADBY_OPERATIONS_REMOTE_STATE_PATH', storage_path('app/private/waadby-operations-agent')),
        'replay_store' => env('WAADBY_OPERATIONS_REMOTE_REPLAY_STORE'),
        'clock_skew_seconds' => min(60, max(0, (int) env('WAADBY_OPERATIONS_REMOTE_CLOCK_SKEW', 30))),
        'maximum_token_ttl_seconds' => min(90, max(30, (int) env('WAADBY_OPERATIONS_REMOTE_TOKEN_TTL', 60))),
        'enrollment_document_maximum_ttl_seconds' => min(300, max(30, (int) env('WAADBY_OPERATIONS_ENROLLMENT_DOCUMENT_TTL', 300))),
        'maximum_body_bytes' => min(1048576, max(1024, (int) env('WAADBY_OPERATIONS_REMOTE_MAX_BODY', 262144))),
        'rate_limit_per_minute' => min(600, max(1, (int) env('WAADBY_OPERATIONS_REMOTE_RATE_LIMIT', 120))),
        'mutation_rate_limit_per_minute' => min(120, max(1, (int) env('WAADBY_OPERATIONS_REMOTE_MUTATION_RATE_LIMIT', 20))),
        'export_rate_limit_per_minute' => min(60, max(1, (int) env('WAADBY_OPERATIONS_REMOTE_EXPORT_RATE_LIMIT', 10))),
        'allow_local_testing_http' => (bool) env('WAADBY_OPERATIONS_REMOTE_ALLOW_LOCAL_HTTP', false),
    ],
    'backup' => [
        'disk' => env('WAADBY_OPERATIONS_BACKUP_DISK', 'local'),
        'directory' => env('WAADBY_OPERATIONS_BACKUP_DIRECTORY', 'waadby-operations/backups'),
        'key' => env('WAADBY_OPERATIONS_BACKUP_KEY'),
        'auto_verify' => true,
        'persistent_paths' => [],
        'sensitive_variables' => [],
        'include_code_snapshot' => false,
        'code_paths' => [],
        'excluded_names' => [
            '.git', '.env', 'vendor', 'node_modules', 'logs', 'cache', 'sessions', 'views', 'backups',
        ],
    ],
    'database' => [
        'enabled' => true,
        'mysqldump_binary' => env('WAADBY_OPERATIONS_MYSQLDUMP', 'mysqldump'),
        'mysql_binary' => env('WAADBY_OPERATIONS_MYSQL', 'mysql'),
    ],
];
